from __future__ import annotations

from io import BytesIO
import importlib.util
from pathlib import Path
import struct
import sys
import xml.etree.ElementTree as ET
import zipfile

COMPONENT = (
    Path(__file__).resolve().parents[1]
    / "deploy/homeassistant/custom_components/ultimate_3d_studio_v6"
)
MODULE_NAME = "ultimate_3d_studio_v6.bambu_project_archive"
SPEC = importlib.util.spec_from_file_location(
    MODULE_NAME,
    COMPONENT / "bambu_project_archive.py",
)
assert SPEC and SPEC.loader
module = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = module
SPEC.loader.exec_module(module)


def sample_gcode(*, object_name: str = "") -> bytes:
    lines = [
        "; generated by Bambu Studio",
        *([f"; object name: {object_name}"] if object_name else []),
        "G90",
        "M82",
        "G92 E0",
        "G1 X10 Y10 F6000",
        "G1 X60 Y10 E2.0 F1200",
        "G1 X60 Y50 E4.0",
        "G1 X10 Y50 E6.0",
        "G1 X10 Y10 E8.0",
    ]
    return ("\n".join(lines) + "\n").encode()


def source_3mf(*names: str) -> bytes:
    objects = "".join(
        (
            f'<object id="{index}" type="model" name="{name}">'
            '<mesh><vertices>'
            '<vertex x="0" y="0" z="0"/>'
            '<vertex x="1" y="0" z="0"/>'
            '<vertex x="0" y="1" z="0"/>'
            '</vertices><triangles>'
            '<triangle v1="0" v2="1" v3="2"/>'
            '</triangles></mesh></object>'
        )
        for index, name in enumerate(names, start=1)
    )
    model = (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<model unit="millimeter" '
        'xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">'
        '<metadata name="Title">Druckplatte 1</metadata>'
        f'<resources>{objects}</resources>'
        '<build><item objectid="1"/></build>'
        '</model>'
    ).encode()
    target = BytesIO()
    with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("3D/3dmodel.model", model)
    return target.getvalue()


def native_sliced_3mf() -> tuple[bytes, bytes, dict[str, bytes]]:
    gcode = sample_gcode(object_name="Brause Quadrat 25")
    preserved = {
        "3D/3dmodel.model": b"native-model",
        "Metadata/plate_1.json": b'{"plate_index":1,"native":true}',
        "Metadata/project_settings.config": b'{"printer_model":"A1"}',
        "Metadata/model_settings.config": b"native-model-settings",
        "Metadata/slice_info.config": b"native-slice-info",
        "Metadata/plate_1.gcode.md5": b"0123456789abcdef0123456789abcdef",
        "_rels/.rels": b"native-relations",
    }
    content_types = (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>'
        '<Default Extension="config" ContentType="application/octet-stream"/>'
        '<Default Extension="gcode" ContentType="text/x.gcode"/>'
        '<Default Extension="json" ContentType="application/json"/>'
        '</Types>'
    ).encode()
    target = BytesIO()
    with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("[Content_Types].xml", content_types)
        for name, value in preserved.items():
            archive.writestr(name, value)
        archive.writestr("Metadata/plate_1.gcode", gcode)
    return target.getvalue(), gcode, preserved


def test_project_name_is_derived_from_actual_3mf_object_name() -> None:
    assert module.project_name_from_3mf(
        source_3mf("Brause Quadrat 25"),
        "Druckplatte 1.3mf",
    ) == "Brause Quadrat 25"


def test_multiple_3mf_objects_get_a_compact_readable_name() -> None:
    assert module.project_name_from_3mf(
        source_3mf("Brause", "Halter", "Deckel"),
        "Druckplatte 1.3mf",
    ) == "Brause +2 Teile"


def test_gcode_object_comment_is_used_when_job_name_is_generic() -> None:
    payload = {
        "job": {
            "input_file": "v6-a1b2c3d4e5-plate-1-Druckplatte_1.3mf",
        }
    }
    assert module.project_name_from_server_payload(
        payload,
        "fallback",
        sample_gcode(object_name="Brause Quadrat 25"),
    ) == "Brause Quadrat 25"


def test_display_ready_archive_contains_exact_gcode_and_thumbnails() -> None:
    gcode = sample_gcode()
    content, filename, digest = module.build_bambu_project_archive(
        "Brause Quadrat",
        gcode,
        "fallback",
    )
    assert filename == "Brause Quadrat.gcode.3mf"
    assert len(digest) == 64

    with zipfile.ZipFile(BytesIO(content)) as archive:
        names = set(archive.namelist())
        assert "Metadata/plate_1.gcode" in names
        assert "Metadata/plate_1.png" in names
        assert "Metadata/plate_1_small.png" in names
        assert "Metadata/plate_no_light_1.png" in names
        assert "Metadata/pick_1.png" in names
        assert archive.read("Metadata/plate_1.gcode") == gcode
        large = archive.read("Metadata/plate_1.png")
        small = archive.read("Metadata/plate_1_small.png")

    assert large.startswith(b"\x89PNG\r\n\x1a\n")
    assert small.startswith(b"\x89PNG\r\n\x1a\n")
    assert struct.unpack(">II", large[16:24]) == (512, 512)
    assert struct.unpack(">II", small[16:24]) == (128, 128)
    assert len(large) > 200


def test_native_bambu_archive_preserves_metadata_and_adds_previews() -> None:
    native, gcode, preserved = native_sliced_3mf()
    content, filename, digest = module.prepare_bambu_project_artifact(
        "Brause Quadrat 25",
        native,
        "fallback",
    )

    assert filename == "Brause Quadrat 25.gcode.3mf"
    assert len(digest) == 64
    assert module.gcode_from_bambu_project_artifact(content) == gcode

    with zipfile.ZipFile(BytesIO(content)) as archive:
        names = set(archive.namelist())
        for name, value in preserved.items():
            assert archive.read(name) == value
        assert archive.read("Metadata/plate_1.gcode") == gcode
        for preview in (
            "Metadata/plate_1.png",
            "Metadata/plate_1_small.png",
            "Metadata/plate_no_light_1.png",
            "Metadata/pick_1.png",
        ):
            assert preview in names
            assert archive.read(preview).startswith(b"\x89PNG\r\n\x1a\n")

        content_types = ET.fromstring(archive.read("[Content_Types].xml"))
        extensions = {
            str(item.attrib.get("Extension") or "").casefold()
            for item in content_types
        }
        assert "png" in extensions


def test_native_gcode_extraction_rejects_multiple_plate_gcodes() -> None:
    target = BytesIO()
    with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("Metadata/plate_1.gcode", sample_gcode())
        archive.writestr("Metadata/plate_2.gcode", sample_gcode())
    try:
        module.gcode_from_bambu_project_artifact(target.getvalue())
    except ValueError as exc:
        assert "genau eine" in str(exc)
    else:
        raise AssertionError("Multiple native G-code entries were accepted")


def test_legacy_raw_gcode_still_uses_fallback_packaging() -> None:
    gcode = sample_gcode()
    content, filename, digest = module.prepare_bambu_project_artifact(
        "Legacy",
        gcode,
        "fallback",
    )
    assert filename == "Legacy.gcode.3mf"
    assert len(digest) == 64
    assert module.gcode_from_bambu_project_artifact(content) == gcode
