from __future__ import annotations

import importlib.util
import io
from pathlib import Path
import sys
import types
import zipfile

import pytest

COMPONENT = (
    Path(__file__).resolve().parents[1]
    / "deploy/homeassistant/custom_components/ultimate_3d_studio_v6"
)
PACKAGE_NAME = "ultimate_3d_studio_v6"
MODULE_NAME = f"{PACKAGE_NAME}.bambu_direct_print"

package = types.ModuleType(PACKAGE_NAME)
package.__path__ = [str(COMPONENT)]
sys.modules.setdefault(PACKAGE_NAME, package)

SPEC = importlib.util.spec_from_file_location(
    MODULE_NAME,
    COMPONENT / "bambu_direct_print.py",
    submodule_search_locations=[str(COMPONENT)],
)
assert SPEC and SPEC.loader
print_artifact = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = print_artifact
SPEC.loader.exec_module(print_artifact)


def rendered_gcode() -> bytes:
    lines = [
        "; generated by Bambu Studio",
        "; complete rendered V6 regression artifact",
        "M1002 gcode_claim_action : 1",
        "G392 S0",
        "M104 S220",
        "M140 S60",
        "M109 S220",
        "M190 S60",
        "M620 S0A",
        "M621 S0A",
        "M1002 judge_flag g29_before_print_flag",
        "G29 A1",
        "M1002 judge_flag extrude_cali_flag",
        "M983 A0",
        "; WIPE NOZZLE",
        "M900 C",
    ]
    lines.extend(f"G1 X{index} Y1 E0.10" for index in range(1, 96))
    lines.extend(["M104 S0", "M140 S0"])
    return ("\n".join(lines) + "\n").encode("utf-8")


def artifact(*, with_preview: bool = False) -> bytes:
    target = io.BytesIO()
    with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("Metadata/plate_1.gcode", rendered_gcode())
        if with_preview:
            archive.writestr("Metadata/plate_1.png", b"PNG")
            archive.writestr("Metadata/plate_1_small.png", b"PNG")
    return target.getvalue()


def uploaded():
    validated = print_artifact.validate_gcode_3mf("beta1.3mf", artifact())
    return print_artifact.UploadedPrintArtifact(
        printer_id="SERIAL",
        remote_filename="beta1.gcode.3mf",
        remote_url="ftp:///beta1.gcode.3mf",
        size_bytes=100,
        sha256="a" * 64,
        gcode_path="Metadata/plate_1.gcode",
        validation_report=validated.validation_report,
    )


def test_valid_single_plate_artifact() -> None:
    data = artifact(with_preview=True)
    result = print_artifact.validate_gcode_3mf("beta1.3mf", data)
    assert result.filename == "beta1.gcode.3mf"
    assert result.gcode_path == "Metadata/plate_1.gcode"
    assert result.size_bytes == len(data)
    assert len(result.sha256) == 64
    assert result.validation_report["line_count"] >= 100
    assert result.validation_report["extrusion_moves"] >= 5
    assert result.validation_report["display_preview_available"] is True
    assert result.validation_report["preview_paths"] == [
        "Metadata/plate_1.png",
        "Metadata/plate_1_small.png",
    ]


def test_project_file_payload_preserves_single_ams_slot_order() -> None:
    payload = print_artifact.build_project_file_command(
        uploaded(),
        use_ams=True,
        ams_mapping=[2],
        bed_leveling=True,
        flow_cali=False,
        vibration_cali=True,
        timelapse=False,
    )["print"]
    assert payload["command"] == "project_file"
    assert payload["file"] == "beta1.gcode.3mf"
    assert payload["url"] == "ftp:///beta1.gcode.3mf"
    assert payload["md5"] == ""
    assert payload["plate_idx"] == 0
    assert payload["param"] == "Metadata/plate_1.gcode"
    assert payload["subtask_name"] == "beta1"
    assert payload["ams_mapping"] == [2]
    assert payload["bed_leveling"] is True
    assert payload["bed_levelling"] is True
    assert payload["vibration_cali"] is True


def test_project_file_payload_preserves_two_ams_slots_in_filament_order() -> None:
    payload = print_artifact.build_project_file_command(
        uploaded(),
        use_ams=True,
        ams_mapping=[0, 1],
        bed_leveling=True,
        flow_cali=False,
        vibration_cali=True,
        timelapse=False,
    )["print"]
    assert payload["ams_mapping"] == [0, 1]
    assert payload["use_ams"] is True


def test_project_file_payload_rejects_external_spool_marker_for_ams_job() -> None:
    with pytest.raises(print_artifact.DirectPrintError, match="externe Spule"):
        print_artifact.build_project_file_command(
            uploaded(),
            use_ams=True,
            ams_mapping=[-1, -1, -1, 0, 1],
            bed_leveling=True,
            flow_cali=False,
            vibration_cali=True,
            timelapse=False,
        )


def test_rejects_invalid_ams_mapping() -> None:
    with pytest.raises(print_artifact.DirectPrintError, match="AMS-Zuordnung"):
        print_artifact.build_project_file_command(
            uploaded(),
            use_ams=True,
            ams_mapping=[256],
            bed_leveling=True,
            flow_cali=False,
            vibration_cali=True,
            timelapse=False,
        )


def test_rejects_empty_ams_mapping_when_ams_is_required() -> None:
    with pytest.raises(print_artifact.DirectPrintError, match="AMS-Zuordnung"):
        print_artifact.build_project_file_command(
            uploaded(),
            use_ams=True,
            ams_mapping=[],
            bed_leveling=True,
            flow_cali=False,
            vibration_cali=True,
            timelapse=False,
        )


def test_ftps_error_classes_are_flat_exception_types() -> None:
    assert print_artifact.FTPS_ERRORS
    assert all(
        isinstance(error_type, type) and issubclass(error_type, BaseException)
        for error_type in print_artifact.FTPS_ERRORS
    )


def test_upload_accepts_data_channel_timeout_after_verified_remote_size(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    data = artifact()

    class TimeoutClient:
        closed = False

        def storbinary(
            self,
            command: str,
            stream: io.BytesIO,
            blocksize: int,
        ) -> None:
            assert command == "STOR beta1.gcode.3mf"
            assert blocksize == 256 * 1024
            assert stream.read() == data
            raise TimeoutError("TLS close-notify missing")

        def close(self) -> None:
            self.closed = True

        def quit(self) -> None:
            raise AssertionError(
                "Timeout connections must be closed without QUIT",
            )

    client = TimeoutClient()
    monkeypatch.setattr(
        print_artifact,
        "_connect_ftps",
        lambda **_kwargs: client,
    )
    monkeypatch.setattr(
        print_artifact,
        "_remote_file_size",
        lambda **_kwargs: len(data),
    )

    result = print_artifact.upload_gcode_3mf(
        host="printer.local",
        access_code="secret",
        printer_id="SERIAL",
        filename="beta1.3mf",
        data=data,
        tls_insecure=True,
    )

    assert client.closed is True
    assert result.size_bytes == len(data)
    assert result.remote_filename == "beta1.gcode.3mf"
    assert result.remote_url == "ftp:///beta1.gcode.3mf"
    assert result.validation_report["line_count"] >= 100


def test_upload_rejects_verified_size_mismatch(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    data = artifact()

    class SuccessfulClient:
        def storbinary(
            self,
            _command: str,
            _stream: io.BytesIO,
            blocksize: int,
        ) -> None:
            assert blocksize == 256 * 1024

        def quit(self) -> None:
            return None

        def close(self) -> None:
            return None

    monkeypatch.setattr(
        print_artifact,
        "_connect_ftps",
        lambda **_kwargs: SuccessfulClient(),
    )
    monkeypatch.setattr(
        print_artifact,
        "_remote_file_size",
        lambda **_kwargs: len(data) - 1,
    )
    monkeypatch.setattr(
        print_artifact,
        "delete_remote_file",
        lambda **_kwargs: True,
    )

    with pytest.raises(print_artifact.DirectPrintError, match="Größenprüfung"):
        print_artifact.upload_gcode_3mf(
            host="printer.local",
            access_code="secret",
            printer_id="SERIAL",
            filename="beta1.3mf",
            data=data,
            tls_insecure=True,
        )

def test_upload_reports_real_monotonic_ftps_byte_progress(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    data = artifact(with_preview=True)
    samples: list[tuple[int, int, str]] = []

    class ProgressClient:
        def storbinary(
            self,
            command: str,
            stream: io.BytesIO,
            blocksize: int,
            callback=None,
        ) -> None:
            assert command == "STOR beta1.gcode.3mf"
            assert blocksize == 256 * 1024
            while block := stream.read(97):
                if callback is not None:
                    callback(block)

        def quit(self) -> None:
            return None

        def close(self) -> None:
            return None

    monkeypatch.setattr(
        print_artifact,
        "_connect_ftps",
        lambda **_kwargs: ProgressClient(),
    )
    monkeypatch.setattr(
        print_artifact,
        "_remote_file_size",
        lambda **_kwargs: len(data),
    )

    result = print_artifact.upload_gcode_3mf(
        host="printer.local",
        access_code="secret",
        printer_id="SERIAL",
        filename="beta1.3mf",
        data=data,
        tls_insecure=True,
        on_progress=lambda loaded, total, stage: samples.append(
            (loaded, total, stage),
        ),
    )

    assert result.size_bytes == len(data)
    assert samples[0] == (0, len(data), "connecting")
    assert samples[-1] == (len(data), len(data), "completed")
    assert "uploading" in [stage for _, _, stage in samples]
    assert "verifying" in [stage for _, _, stage in samples]
    loaded_values = [loaded for loaded, _, _ in samples]
    assert loaded_values == sorted(loaded_values)
    assert all(total == len(data) for _, total, _ in samples)

