from __future__ import annotations

from io import BytesIO
import importlib.util
from pathlib import Path
import sys

import pytest

COMPONENT = (
    Path(__file__).resolve().parents[1]
    / "deploy/homeassistant/custom_components/ultimate_3d_studio_v6"
)
MODULE_NAME = "ultimate_3d_studio_v6.gcode_artifact_validation"
SPEC = importlib.util.spec_from_file_location(
    MODULE_NAME,
    COMPONENT / "gcode_artifact_validation.py",
)
assert SPEC and SPEC.loader
validation = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = validation
SPEC.loader.exec_module(validation)


def complete_gcode(extra_line: str) -> BytesIO:
    lines = [
        "; generated by Bambu Studio",
        extra_line,
        "M1002 gcode_claim_action : 1",
        "G392 S0",
        "M104 S220",
        "M140 S60",
        "M109 S220",
        "M190 S60",
        "M620 S0A",
        "M621 S0A",
        "M1002 judge_flag g29_before_print_flag",
        "G29 A1",
        "M1002 judge_flag extrude_cali_flag",
        "M983 A0",
        "; WIPE NOZZLE",
        "M900 C",
    ]
    lines.extend(f"G1 X{index} Y1 E0.10" for index in range(1, 96))
    lines.extend(["M104 S0", "M140 S0"])
    return BytesIO(("\n".join(lines) + "\n").encode("utf-8"))


def test_comment_only_filename_template_is_allowed() -> None:
    report = validation.validate_rendered_bambu_gcode(
        complete_gcode(
            "; filename_format = "
            "{input_filename_base}_{filament_type[0]}_{print_time}.gcode"
        )
    )
    assert report.line_count >= 100
    assert report.extrusion_moves >= 5
    assert report.markers["machine_shutdown_hotend"] is True
    assert report.markers["machine_shutdown_bed"] is True


def test_executable_unresolved_temperature_template_is_rejected() -> None:
    with pytest.raises(
        validation.GCodeValidationError,
        match="Profil-Template-Platzhalter nicht aufgelöst",
    ):
        validation.validate_rendered_bambu_gcode(
            complete_gcode("M104 S{nozzle_temperature[0]}")
        )
