from __future__ import annotations

from io import BytesIO
import importlib.util
from pathlib import Path
import sys

import pytest

COMPONENT = (
    Path(__file__).resolve().parents[1]
    / "deploy/homeassistant/custom_components/ultimate_3d_studio"
)
MODULE_NAME = "ultimate_3d_studio.gcode_artifact_validation"
SPEC = importlib.util.spec_from_file_location(
    MODULE_NAME,
    COMPONENT / "gcode_artifact_validation.py",
)
assert SPEC and SPEC.loader
validation = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = validation
SPEC.loader.exec_module(validation)


def complete_gcode(extra_line: str) -> BytesIO:
    lines = [
        "; generated by Bambu Studio",
        extra_line,
        "M1002 gcode_claim_action : 1",
        "G392 S0",
        "M104 S220",
        "M140 S60",
        "M109 S220",
        "M190 S60",
        "M620 S0A",
        "M621 S0A",
        "M1002 judge_flag g29_before_print_flag",
        "G29 A1",
        "M1002 judge_flag extrude_cali_flag",
        "M983 A0",
        "; WIPE NOZZLE",
        "M900 C",
    ]
    lines.extend(f"G1 X{index} Y1 E0.10" for index in range(1, 96))
    lines.extend(["M104 S0", "M140 S0"])
    return BytesIO(("\n".join(lines) + "\n").encode("utf-8"))


def test_comment_only_filename_template_is_allowed() -> None:
    report = validation.validate_rendered_bambu_gcode(
        complete_gcode(
            "; filename_format = "
            "{input_filename_base}_{filament_type[0]}_{print_time}.gcode"
        )
    )
    assert report.line_count >= 100
    assert report.extrusion_moves >= 5
    assert report.markers["machine_shutdown_hotend"] is True
    assert report.markers["machine_shutdown_bed"] is True


def test_executable_unresolved_temperature_template_is_rejected() -> None:
    with pytest.raises(
        validation.GCodeValidationError,
        match="Profil-Template-Platzhalter nicht aufgelöst",
    ):
        validation.validate_rendered_bambu_gcode(
            complete_gcode("M104 S{nozzle_temperature[0]}")
        )


H2S_LIMITS = {"max_nozzle_temperature_c": 350., "max_bed_temperature_c": 120.,
              "max_chamber_temperature_c": 65., "width_mm": 340.,
              "depth_mm": 320., "height_mm": 340.}


def h2s_gcode(extra: str = "") -> BytesIO:
    source = complete_gcode("; printer_model = Bambu Lab H2S").getvalue().decode()
    source = source.replace("M983 A0", "M983.3 F5 A0.4")
    source = source.replace("; WIPE NOZZLE", "G150 T220")
    source = source.replace("M900 C", ";===== nozzle load line =====\nG1 X290 E20 F600\n;===== noozle load line end =====")
    return BytesIO((source + extra).encode())


def test_h2s_firmware_sequence_with_explicit_hardware_authority() -> None:
    report = validation.validate_rendered_bambu_gcode(
        h2s_gcode(), hardware_limits=H2S_LIMITS, expected_printer_model="H2S")
    assert report.declared_printer_model == "Bambu Lab H2S"
    assert all(report.markers.values())


@pytest.mark.parametrize("command", ["G150 T351", "M620.10 A0 T351 P220", "M620.15 C351",
    "M620.10 A1 T240 P351", "M141 S66", "M191 R66", "G150 TNaN",
    "M620.10 A0 TInf P220", "M141 S-1"])
def test_h2s_firmware_heaters_cannot_bypass_temperature_checks(command: str) -> None:
    with pytest.raises(validation.GCodeValidationError):
        validation.validate_rendered_bambu_gcode(
            h2s_gcode(command + "\n"), hardware_limits=H2S_LIMITS, expected_printer_model="H2S")


@pytest.mark.parametrize("key,value", [("max_nozzle_temperature_c",351),
    ("max_chamber_temperature_c",66), ("width_mm",350), ("height_mm",float("nan")),
    ("depth_mm",True)])
def test_h2s_claimed_hardware_cannot_raise_physical_limits(key: str, value: object) -> None:
    limits = {**H2S_LIMITS, key: value}
    with pytest.raises(validation.GCodeValidationError, match="H2S-Hardwaregrenze"):
        validation.validate_rendered_bambu_gcode(
            h2s_gcode(), hardware_limits=limits, expected_printer_model="H2S")


@pytest.mark.parametrize("removed", ["M983.3 F5 A0.4", "G150 T220", "G1 X290 E20 F600"])
def test_h2s_descriptive_metadata_does_not_replace_executed_sequence(removed: str) -> None:
    altered = h2s_gcode().getvalue().replace(removed.encode(), ("; " + removed).encode())
    with pytest.raises(validation.GCodeValidationError, match="Maschinenablauf ist unvollständig"):
        validation.validate_rendered_bambu_gcode(
            BytesIO(altered), hardware_limits=H2S_LIMITS, expected_printer_model="H2S")


def test_h2s_declaration_does_not_grant_hardware_authority() -> None:
    with pytest.raises(validation.GCodeValidationError, match="explizite Hardware"):
        validation.validate_rendered_bambu_gcode(h2s_gcode(), expected_printer_model="H2S")


# Regression: an actual one-layer test has no subsequent-layer bed phase.
ONE_LAYER_BED_PARAMETERS = [{"textured_plate_temp": ["55"], "textured_plate_temp_initial_layer": ["60"]}]


def one_layer_bed_gcode(*, total: int = 1, second_layer: bool = False, second_z: bool = False) -> BytesIO:
    source = complete_gcode("; printer_model = Bambu Lab A1").getvalue().decode()
    source = source.replace("G1 X1 Y1 E0.10", (
        f"; total layer number: {total}\n"
        "; textured_plate_temp = 55\n; textured_plate_temp_initial_layer = 60\n"
        "G90\nM83\nG1 Z0.2\n; MACHINE_START_GCODE_END\n"
        "; CHANGE_LAYER\nG1 X1 Y1 E0.10"))
    if second_layer:
        source = source.replace("G1 X50 Y1 E0.10", "; CHANGE_LAYER\nG1 Z0.4\nG1 X50 Y1 E0.10")
    elif second_z:
        source = source.replace("G1 X50 Y1 E0.10", "G1 Z0.4\nG1 X50 Y1 E0.10")
    return BytesIO(source.encode())


def check_layer_bed(source: BytesIO):
    return validation.validate_rendered_bambu_gcode(
        source, runtime_parameters=ONE_LAYER_BED_PARAMETERS,
        expected_bed_temperature_key="textured_plate_temp")


def test_single_layer_bed_does_not_require_nonexistent_following_layer_phase() -> None:
    report = check_layer_bed(one_layer_bed_gcode())
    assert report.filament_parameter_contract_verified
    assert report.checked_print_extrusion_moves == 95


@pytest.mark.parametrize("total,second_layer,second_z", [(2,True,False),(1,True,False),(1,False,True),(2,False,False)])
def test_multilayer_or_forged_single_layer_still_requires_regular_bed_heat(total, second_layer, second_z) -> None:
    with pytest.raises(validation.GCodeValidationError, match="textured_plate_temp wurde nicht"):
        check_layer_bed(one_layer_bed_gcode(total=total,second_layer=second_layer,second_z=second_z))


def test_single_layer_still_requires_initial_bed_heat() -> None:
    source = one_layer_bed_gcode().getvalue().replace(b"M140 S60", b"M140 S55").replace(b"M190 S60", b"M190 S55")
    with pytest.raises(validation.GCodeValidationError, match="textured_plate_temp_initial_layer wurde nicht"):
        check_layer_bed(BytesIO(source))


def test_single_layer_still_rejects_changed_native_parameters() -> None:
    source = one_layer_bed_gcode().getvalue().replace(b"; textured_plate_temp = 55", b"; textured_plate_temp = 54")
    with pytest.raises(validation.GCodeValidationError, match="nicht unverändert übernommen"):
        check_layer_bed(BytesIO(source))


def test_single_layer_still_enforces_hardware_temperature_limit() -> None:
    source = one_layer_bed_gcode().getvalue() + b"M140 S101\n"
    with pytest.raises(validation.GCodeValidationError, match="Druckbett"):
        check_layer_bed(BytesIO(source))


def test_multilayer_with_both_bed_setpoints_remains_valid() -> None:
    source = one_layer_bed_gcode(total=2,second_layer=True).getvalue().replace(b"G1 Z0.4", b"M140 S55\nG1 Z0.4")
    assert check_layer_bed(BytesIO(source)).filament_parameter_contract_verified


def test_original_unified_preview_progress_and_renderer_remain_wired() -> None:
    root = COMPONENT.parents[3]
    entry = (root / "frontend/studio-entry.ts").read_text()
    assert entry.count("<ultimate-3d-global-job-popup></ultimate-3d-global-job-popup>") == 1
    assert "<studio-preview-progress-popup" not in entry
    popup = (root / "frontend/global-job-popup-v3.ts").read_text()
    assert "const previewCard = visiblePreview" in popup
    assert "(loadedLayers / layerCount) * 100" in popup
    assert "#previewWorkflowKey(): string" in popup
    workspace = (root / "frontend/studio-mega-workspace-v2.ts").read_text()
    assert '"toolpath_parse_started"' in workspace
    assert "buildContinuousToolpathMeshes" in workspace


def test_forged_single_layer_with_closed_arc_on_second_plane_is_rejected() -> None:
    source = one_layer_bed_gcode().getvalue().replace(
        b"G1 X50 Y1 E0.10", b"G1 Z0.4\nG2 X49 Y1 I1 J0 E1\nG1 Z0.2\nG1 X50 Y1 E0.10")
    with pytest.raises(validation.GCodeValidationError, match="textured_plate_temp wurde nicht"):
        check_layer_bed(BytesIO(source))
